# Generated by Django 5.2 on 2025-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_trades', '0002_rename_cargo_name_buyertransactionspr_buyer_any_deductions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyertransactionspr',
            old_name='buyer_Fixed_pricing_period_to',
            new_name='buyer_fixed_pricing_period_to',
        ),
        migrations.RenameField(
            model_name='buyertransactionspr',
            old_name='buyer_Pricing_Unit1',
            new_name='buyer_pricing_unit1',
        ),
    ]
