# Generated by Django 5.2 on 2025-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_trades', '0003_rename_buyer_fixed_pricing_period_to_buyertransactionspr_buyer_fixed_pricing_period_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_column', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DemSellerTransactionSpr',
            new_name='SellerTransactionSpr',
        ),
    ]
