# Generated by Django 5.2 on 2025-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_trades', '0005_remove_buyertransactionspr_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellertransactionspr',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sellertransactionspr',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='accepted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='accounting_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='afra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='ai_deesc1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='buyer_pricing_unita1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='cargo_financial_hold',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='charterparty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='compleetion_dis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='contract_counterparty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='counterparty_fef1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='demurrage_calculations_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='demurrage_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='destination_port',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='documentary_instructions_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='esc_deesc1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='euro_conv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='euro_conv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='euro_conv_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='euro_conv_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='freight_component',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='gtc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='inspection_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='insurance_instructions_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='invoice_payment_received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='invoice_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='kin_deesc1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='laytime_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='lc_format_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='lc_received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='loadport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='nomination_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='nor_desination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='percentage1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='prepayment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='prepayment_period2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='price_calculations_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='price_declared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_contract_specific_gravity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_delivery_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_delivery_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_invoice_qtybasis1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_loaded_specific_gravity',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_payment_invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_price_calculation_density',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_pricing_quotes1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_pricing_unit_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_pricing_unita',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='seller_pricing_unita1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='time_bar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='timebar_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='transfer_title_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellertransactionspr',
            name='voyage_orders_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
