# Generated by Django 5.2 on 2025-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_trades', '0006_remove_sellertransactionspr_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertransactionspr',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sellertransactionspr',
            name='email_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
