# Generated by Django 5.2 on 2025-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_trades', '0007_buyertransactionspr_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertransactionspr',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellertransactionspr',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
