# Generated by Django 5.2 on 2025-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0007_delete_interimtransactionspr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingspr',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='quantity_mt',
            field=models.IntegerField(null=True),
        ),
    ]
