# Generated by Django 5.2 on 2025-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0008_alter_hedgingspr_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgingspr',
            name='quantitybbl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
