# Generated by Django 5.2 on 2025-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0009_hedgingspr_quantitybbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingspr',
            name='traded_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
