# Generated by Django 5.2 on 2025-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0011_alter_hedgingspr_traded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingspr',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='traded_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
