# Generated by Django 5.2 on 2025-05-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0012_alter_hedgingspr_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hedgingspr',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='hedgingspr',
            name='date_modified',
        ),
    ]
